# -*- coding: utf-8 -*-
"""get_trials.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w0Vtc_7FdOZG5kVC8WaL5IqC6UfBPKFM
"""

'''
This code is used to download the data from the ClinicalTrials.gov API.
The data essentially refers to the clinical trials pertaining to a particular health condition given as user input.
The data is downloaded as an XML file.
'''
import requests


def download_result(filename, content):
    with open('./data/{}.xml'.format(filename), 'w') as file:
        file.write(content)


def main():
    # Take the health condition as input from the user
    health_condition = input("Enter the health condition: ")

    url = "https://clinicaltrials.gov/api/query/study_fields"

    params = {
        'expr': health_condition,
        'fields': 'NCTId,BriefTitle,Condition,EligibilityCriteria',
        'min_rnk': '2',
        'max_rnk': '21',
        'fmt': 'xml'
    }

    headers = {
        'Cookie': 'CTOpts=Qihzm6CLCwL6zw5G6yUgzw-R98F5OR4PNDWl; Psid=vihzm6CLCwL6zw5G6yz3FQ7V9ghH0gFRxR4waBFHkR0y0gzqaR78xBCGCD8V'
    }

    response = requests.get(url, params=params, headers=headers)

    if response.status_code == 200:
        data = response.text
        download_result("full_studies", data)
        print("Data downloaded successfully.")
    else:
        print(f"Error: {response.status_code}. Unable to fetch data.")


if __name__ == "__main__":
    main()